name: Build & Test

on: [push, pull_request]

jobs:
  test-and-coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.4
      - name: Run cross-version tests
        run: sbt +test
      - name: Run coverage
        run: sbt coverage test
      - name: Coverage Report
        run: sbt coverageReport
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3.1.1
        with:
          fail_ci_if_error: true
#  lint:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v4.1.4
#      - name: Formatting
#        run: sbt scalafmtSbtCheck scalafmtCheck test:scalafmtCheck